version: '3.6'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    networks:
      - app-network
    links:
      - "redis"
      - "db"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/build/
      - server_ssh_key:/root/.ssh
    depends_on:
      - db
      - redis
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:eP8NHS4WBe5Ay3@db:5432/ledokku?schema=public&connect_timeout=300
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=SEcreT
      - GITHUB_APP_ID=241254
      - GITHUB_APP_NAME=overclock-studios-paas
      - GITHUB_APP_CLIENT_ID=Iv1.b4e652990b5a1806
      - GITHUB_APP_CLIENT_SECRET=78ff440f64347f9251d5e2e622acd29959cfae96
      - GITHUB_APP_WEBHOOK_SECRET=ocstudios_123
      - GITHUB_APP_PEM=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNGovYW1qanIvMWZHWjNONndoMHFiSDVKNmtNQWFQM0kxUk52L1hNaWRmS1BnY083CmYxQis3TUV0WnNlQUI3RHBUVkQwNjNIZkw5RUh6bzNCUnQ2VlUxalZnbnFMbTRRSFdmbWQxRjYzdk83QUFhSGkKZy90ZGh2eTBYb3k0QXJEcmNnYTFhSDl6MHZKRTZOZFBuQmFPQUFLMXU3OWpXZVF3QlFDMTNzVEdNMXJ6OS9EYgpYMWx4QmlzaVZGaGxTNk1qOXdWbnBLcDdEcmduVlczQmRzQlF6RjMrS3k3T2VST0F5L3U5U1FYOFA0aDNKdEFKCnhIc2xoeFN1M3hvSW1Jd1Q4NmhhUTZSYlhJZndYYWJtV2ZLQ0JOZFB3cGYwdE16RDlpSW1TVjlVTzRCMDJ2MmEKZlhhSFk1dlNPRU0xTGErdnVYajVQa3h3bzJhMzB0SlVFRWdueXdJREFRQUJBb0lCQVFEYURjYW5Hck5CRHB5Mgp1ZEtYWVRxeEErcERNRDRsOG1wc0NlYkdjLy9EZzNxU0MwNGEvejdFK2MzRElBV2g0L3lHdXI3Q2FLWTlWSTNjCm9qeWtEQVFKSnpYb0lpbUpRZTgvNVZjYkJncTV1YlV1SFpMTnR5YkY0YW9JOGtDcXYwNjhRQUQ0N05WNWVtdTEKcVVZZDNwTVBLWTF6bkpxcFdVWjZtOXV0RHlNaSsvYXpzbngzQjlEK3NjbG5QaWVQdmplSlRjUTkwdEIxTHFwNApPZWttQkFOTThKbHZidGxDR3QzcmpoWElkWldGZWVVN0VUT0ZFdnp2ODVzQjA0eGhzUnNkSkQzdHBNNXhKbThTCkZxaDZQTHgzb2NKWlprM0duK3hrS3U3ZXNiUjRnRFM5KzFTZGNGaTJkUGtaQUwveTV0RmlIZks1b2NQS2pjK28KTzV4SXcwWXBBb0dCQVBsTkwvSXozRzFKMzUrRFlDQkx2RFhsY1VSUUNQT0NGWW9XZHNvNlJZQUpvWVBqVVB4Uwp5NjV0M1Rja3JLMEVPMkdjdlRsYzFmRFFlUnl1cGVQUFkrVFQxc1hqSGRVY0lCNldZZENBNlBndUhIS3QzcE15ClQ1NEE0cmtMVDZVQ2Y3am04SDZnaEVCZSsrUzcvNFdqa0RVMWRvMFJSSTFGYng3Sjc5bzJhdnpsQW9HQkFPaFUKR29TZjkyNTFDMFF6aDA0UkRSM0NIa1krcmY3U082RDNrTDlZZVNQcW1SUENnMnB5Q2ZDN0p1TlZwLytwck1mbApaT0dLTkFpbU54T3lnQThHTW9NTmpPS0tLOU51NHN0N1llcUhtbmlYZlc2cEJGVVpobnlBWDd5MUNQQ0pPS1Q0CjFtY3JPZThXd2xicGk5UlRkdzhPLzNMRGhGVi9sNi9GbW91UnV2YnZBb0dBTm14dVVoNldPVm1PTXdGNEk3VEUKNHJNekZlbXUrcEhrWjkvZGtPcEZyOXpxWUtOb1U1MHpqK0cyRUVxMlU1TC83NkJMQXRITWRxVGNPN0c0ejFIQQpDZjFnL3BSRk4vZkszMEtQR2ZoNlkydVZsRWQydG9XZU1lMFprYkh4Y2lGb2hwSUw0R2prVmpVbUlsb1VQelZrCnp1amI5NUhVZUU2M0ltNk5LUU1HT2kwQ2dZRUFwZkhrMnhSVHJOOEhSQmkyTFltNlg2WVc3Nysza2tyaDhwREMKSUJwMnRMUE4wVEpmb2JtQTVpVVhtc3ZFNnJWc1IzL1BkZFc4WXUwdWEvQlV6ZVowVCsxdTB5VTBOcHArZmk5TAoralFQbnRFOTg3dmY3MVVESFl5b1ZXYk4wdG1BenowNkQ0anRvWndWQmZWZFBqUzcxdEswbldtUDdXM3NqODFLCkhTVGpjWnNDZ1lFQWcxbjR5MnJ5S0JCazJlczA4bDc1ZmdBc0ZWT3d4TXdUV3h2MExRczY5a0RBdXVxdjI3SzAKbXVkVlFOYitBR05rczN0L3lyRDF6SjRJbTlIaExtVEVaakROeExoZXVvdTNRRXhPVTk5eVppdkVCNUk1VVVkYQpSRDVjSVZ1eWVFZzJwYWtnVFZRdWo2RmNLMU5DeXNlUnV6d3FNdURFOVpYM1BzSjZIaVpnVm13PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
      - DOKKU_SSH_HOST=dokku
      - DOKKU_SSH_PORT=22
      - NUMBER_USERS_ALLOWED=1
      - TELEMETRY_DISABLED=1

  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: eP8NHS4WBe5Ay3

  redis:
    restart: always
    image: 'redis:6'
  
  webserver:
      image: nginx:mainline-alpine
      container_name: webserver
      restart: unless-stopped
      ports:
        - "4000:4000"
        - "4443:4443"
      volumes:
        - web-root:/var/www/html
        - ./nginx-conf:/etc/nginx/conf.d
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
        - dhparam:/etc/ssl/certs
      depends_on:
        - server
      networks:
        - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email contacto@ocstudios.mx --agree-tos --no-eff-email --staging -d ocstudios.mx  -d www.ocstudios.mx

volumes:
  db_data:
  server_ssh_key:
  certbot-etc:
  certbot-var:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ocstudios/ledokku/dhparam/
      o: bind

networks:
  app-network: