version: '3.6'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    ports:
      - '8070:8070'
    restart: unless-stopped
    environment:
      - PORT=80
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_URL=
      - NEXT_PUBLIC_GITHUB_APP_ID=
      - NEXT_PUBLIC_GITHUB_APP_NAME=
      - NEXT_PUBLIC_GITHUB_APP_CLIENT_ID=

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '4000:4000'
      - "80:80"
      - "443:443"
    links:
      - "redis"
      - "db"
    restart: unless-stopped
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/build/
      - server_ssh_key:/root/.ssh
      - /var/lib/dokku:/mnt/dokku
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
    environment:
      - PORT=4000
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:eP8NHS4WBe5Ay3@db:5432/ledokku?schema=public&connect_timeout=300
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=SEcreT
      - GITHUB_APP_ID=
      - GITHUB_APP_NAME=
      - GITHUB_APP_CLIENT_ID=
      - GITHUB_APP_CLIENT_SECRET=
      - GITHUB_APP_WEBHOOK_SECRET=
      - GITHUB_APP_PEM=
      - DOKKU_SSH_HOST=localhost
      - DOKKU_SSH_PORT=22
      - NUMBER_USERS_ALLOWED=1
      - TELEMETRY_DISABLED=1
      - DOKKU_HOSTNAME=dev.ocstudios.mx
      - DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku

  db:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: eP8NHS4WBe5Ay3

  redis:
    restart: always
    image: 'redis:6'
    ports:
      - '6379:6379'

volumes:
  db_data:
  server_ssh_key:
