name: Deploy Ledokku

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sudo su
          cd ${{ secrets.LEDOKKU_PATH }}
          git fetch
          git pull
          printf "${{ secrets.PASSWORD }}\n" | sudo -S docker compose down
          printf "${{ secrets.PASSWORD }}\n" | sudo -S docker compose build --no-cache
          printf "${{ secrets.PASSWORD }}\n" | sudo -S docker compose up